### ISSUE TITLE
I edited script 3 and put some into script 4

### ISSUE THREAD

**Issue by tungpatrick** [UBC-MDS/sylvia_patrick_Titanic_Survival_ML#17]
Some issues I need to talk to you about. I felt that it was incorrect for us to put the calculations of accuracies and feature rankings in script 3. I have now moved them to script 4, but now there is a problem. Since script 4 currently does not have the script 3 tree, we are unable to run feature_rank, nor are we able to generate a decision tree. Do you know if there is any fix for this? Please help!

**Comment by LeeYinYing** [comment]
I think we can use the pickle package to do that. I will merge the pull request and see if I can figure it out

**Comment by LeeYinYing** [comment]
#18 I sent a pull request about this

**Comment by tungpatrick** [comment]
Thank you! I read into it. It seems like exactly what we needed.
