### ISSUE TITLE
Lab Peer Feedback

### ISSUE THREAD

**Issue by tungpatrick** [UBC-MDS/sylvia_patrick_Titanic_Survival_ML#33]
1. We should mention the type of variables (e.g. categorical, ordinal, numeric)
2. We should explain the inputs and outputs of our README usage scripts
3. We COULD graph out a snippet of our decision tree in the report.
4. Make sure to perform grammar and spelling checks.
5. Maybe we could include the figures in the report rather than the appendix. We can make the figures smaller. (suggestion)

**Comment by LeeYinYing** [comment]
see other issue. We complied them together #34
