### ISSUE TITLE
Peer review issues from my side

### ISSUE THREAD

**Issue by LeeYinYing** [UBC-MDS/sylvia_patrick_Titanic_Survival_ML#34]
- Add a graph or description on how we arrived at the optimal max_depth. 
    - show the accuracy scores from the cross-validation or give the graph
- Table 4: why is there code on top? remove it if not needed
- README should add description of the input and output of each command line
- Putting graphs in the appendix is good

**Comment by tungpatrick** [comment]
After our long discussion, we have concluded that we will do the following:
1. Perform spelling and grammar checks
2. Show the inputs and outputs of each command line
3. Remove the code on top of Table 4
4. Add a graph of description on how we arrived at the optimal max_depth
5. Add type of variable to README and report
6. Rename script names to be consistent +  index
7. Rename figure/plot names to be consistent + index

Suggestion we chose not to follow:
1. Move figures from appendix to the actual report
2. Graph a snippet of the decision tree. We personally feel that it is much more effective to reference the full decision tree to see how our model classifiers the data. Instead, we will make sure to add reference to the link of the image.

**Comment by LeeYinYing** [comment]
I will work on everything related to the README first. So that would be #2 and #5 in the list.
